### ISSUE TITLE
Powerline only shows cpu stats

### ISSUE THREAD

**Issue by robeerob** [tony/tmux-config#23]
Hi. I installed the config, and added powerline with pip. Got 'powerline-config tmux setup' returned 127 error. Tried to run the daemon, but said it wasn't installed, so I installed it with sudo apt-get install powerline.

The powerline now works great, except I can only see the cpu stats, and nothing for memory. At least I think that's the case. Here is a screenshot attached. Please advice if I can change this in .tmux.conf or elsewhere.
![screenshot from 2016-01-25 22-34-28](https://cloud.githubusercontent.com/assets/13132899/12565353/7916e986-c3b4-11e5-9c1b-f00909840f14.png)

**Comment by robeerob** [comment]
Might it have to do with the ubuntu repository powerline having different output than the pip powerline?

Here is the output from 'tmux-mem-cpu-load uptime':
2116/15969MB [          ]   5.1%

Occasionally it also has a pipe within the brackets:
2101/15969MB [|         ]   7.3%

**Comment by tony** [comment]
Double check its not the width of your terminal's window, just to be sure.

What version of powerline you using in ubuntu? ``tmux -V``, ``[sudo] lsb_release -a``?

tmux-mem-cpu-load and the powerline are both third party apps. Can you show what your .tmux.conf looks like?

**Comment by robeerob** [comment]
The width is not the problem - no memory stats even on 1920x1080.

I am on tmux 2.0, and Ubuntu wily 15.10.

Here is my .tmux.conf:

`# https://github.com/seebi/tmux-colors-solarized/blob/master/tmuxcolors-256.conf
set-option -g status-bg colour235 #base02
set-option -g status-fg colour136 #yellow
set-option -g status-attr default

# set window split
bind-key v split-window -h
bind-key b split-window

# default window title colors
set-window-option -g window-status-fg colour244 #base0
set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg colour166 #orange
set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg colour166 #orange

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange
# clock
set-window-option -g clock-mode-colour green #green


set -g status-interval 1
set -g status-justify centre # center align window list
set -g status-left-length 20
set -g status-right-length 140
set -g status-left '#[fg=green]#H #[fg=black]• #[fg=green,bright]#(uname -r | cut -c 1-6)#[default]'
set -g status-right '#[fg=green,bg=default,bright]#(tmux-mem-cpu-load) #[fg=red,dim,bg=default]#(uptime | cut -f 4-5 -d " " | cut -f 1 -d ",") #[fg=white,bg=default]%a%l:%M:%S %p#[default] #[fg=blue]%Y-%m-%d'

# C-b is not acceptable -- Vim uses it
set-option -g prefix C-a
bind-key C-a last-window

# Start numbering at 1
set -g base-index 1

# Allows for faster key repetition
set -s escape-time 0

# Rather than constraining window size to the maximum size of any client 
# connected to the *session*, constrain window size to the maximum size of any 
# client connected to *that window*. Much more reasonable.
setw -g aggressive-resize on

# Allows us to use C-a a <command> to send commands to a TMUX session inside 
# another TMUX session
bind-key a send-prefix

# Activity monitoring
setw -g monitor-activity on
set -g visual-activity on

# Vi copypaste mode
set-window-option -g mode-keys vi
bind-key -t vi-copy 'v' begin-selection
bind-key -t vi-copy 'y' copy-selection

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# set to main-horizontal, 60% height for main pane
bind m set-window-option main-pane-height 60\; select-layout main-horizontal

bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"

# reload config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# auto window rename
set-window-option -g automatic-rename

# color
set -g default-terminal "screen-256color"

# status bar
set-option -g status-utf8 on

# https://github.com/edkolev/dots/blob/master/tmux.conf
# Updates for tmux 1.9's current pane splitting paths.

# from powerline
run-shell "tmux set-environment -g TMUX_VERSION_MAJOR $(tmux -V | cut -d' ' -f2 | cut -d'.' -f1 | sed 's/[^0-9]*//g')"
run-shell "tmux set-environment -g TMUX_VERSION_MINOR $(tmux -V | cut -d' ' -f2 | cut -d'.' -f2 | sed 's/[^0-9]*//g')"

# rm mouse mode fail
if-shell '\( #{$TMUX_VERSION_MAJOR} -eq 2 -a #{$TMUX_VERSION_MINOR} -ge 1\) -o #{$TMUX_VERSION_MAJOR} -gt 2' 'set -g mouse off'
if-shell '\( #{$TMUX_VERSION_MAJOR} -eq 2 -a #{$TMUX_VERSION_MINOR} -lt 1\) -o #{$TMUX_VERSION_MAJOR} -le 1' 'set -g mode-mouse off'

# fix pane_current_path on new window and splits
if-shell "#{$TMUX_VERSION_MAJOR} -gt 1 -o \( #{$TMUX_VERSION_MAJOR} -eq 1 -a #{$TMUX_VERSION_MINOR} -ge 8 \)" 'unbind c; bind c new-window -c "#{pane_current_path}"'
if-shell "#{$TMUX_VERSION_MAJOR} -gt 1 -o \( #{$TMUX_VERSION_MAJOR} -eq 1 -a #{$TMUX_VERSION_MINOR} -ge 8 \)" "unbind '\"'; bind '\"' split-window -v -c '#{pane_current_path}'"
if-shell "#{$TMUX_VERSION_MAJOR} -gt 1 -o \( #{$TMUX_VERSION_MAJOR} -eq 1 -a #{$TMUX_VERSION_MINOR} -ge 8 \)" 'unbind v; bind v split-window -h -c "#{pane_current_path}"'
if-shell "#{$TMUX_VERSION_MAJOR} -gt 1 -o \( #{$TMUX_VERSION_MAJOR} -eq 1 -a #{$TMUX_VERSION_MINOR} -ge 8 \)" 'unbind %; bind % split-window -h -c "#{pane_current_path}"'

# pip install --user git+git://github.com/powerline/powerline
# sudo apt-get install powerline
run-shell "powerline-daemon -q"
source-file "/home/rob/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"

# initialize session
bind S source-file ~/.tmux/session1`

**Comment by tony** [comment]
Does this happen without powerline? If you were to commend out:

```
run-shell "powerline-daemon -q"
source-file "/home/rob/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"
```

to 

```
# run-shell "powerline-daemon -q"
# source-file "/home/rob/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"
```

Close all tmux clients, and start a new one?

**Comment by robeerob** [comment]
Yes, I can see it without the powerline. See screenshot attached.
![screenshot from 2016-01-31 16-28-43](https://cloud.githubusercontent.com/assets/13132899/12703097/35b23a62-c83a-11e5-93b0-6789a298585b.png)

**Comment by yfyang86** [comment]
Hi, I came across similar problem. 
I though I quit all tmux clients, but it is not the case. There are still tmux processes running. You could try `killall tmux`, and also kill poweline (with  `ps -ef | grep "powerline"` and kill the PID), then restart tmux `tmux`. This works in my case.

**Comment by tony** [comment]
> I though I quit all tmux clients,

So ``tmux attach`` won't connect to anything?  tmux will continue to run background until all sessions/windows/panes are closed.

I'm still trying to determine if this is a problem with the config, its instructions, powerline or tmux.

There are a couple of options - you're not just boxed into using powerline using this config (or tmux at all for that matter).
