### ISSUE TITLE
tmux pane does not respond

### ISSUE THREAD

**Issue by fabioperez** [tony/tmux-config#27]
Sometimes (it seems random), my tmux panes do not respond to any command after it finishes running a command.

For example, after I run `ls`, the tmux does not respond to any key despite printing everything that I type. `Ctrl+C` does nothing.

[![enter image description here][1]][1]

I use zsh as my default shell. I'm not sure if this is a bug with zsh or tmux. Anyone knows a solution for this?

My setup:

    tmux 2.2 (also tested with tmux 1.8)
    zsh 5.0.2 (x86_64-pc-linux-gnu) (with Prezto)
    
[This issue](https://github.com/tmux/tmux/issues/496) was firstly posted to tmux repo, but I could not reproduce using without the tmux.conf. Also, maybe this is a problem with zsh.

  [1]: http://i.stack.imgur.com/CXXkv.png

**Comment by tony** [comment]
Can you try ``mv ~/.zshrc ~/.zshrc.bak`` so you can load w/o the zsh config?

Try to use preferences (Cmd-P) in Terminal.app / iterm to use ``/bin/bash`` by default temporarily so you can debug.

![image](https://cloud.githubusercontent.com/assets/26336/17589532/f8fdcf0c-5f9a-11e6-9f24-bfa245ccff10.png)

**Comment by fabioperez** [comment]
I think this is a [problem with zsh](https://github.com/sorin-ionescu/prezto/issues/888). I will try to update it to a newer version.

**Comment by fabioperez** [comment]
It is actually a [problem with zsh](https://github.com/sorin-ionescu/prezto/issues/888).
