### ISSUE TITLE
set pane-base-index to 1 to fix tmuxinator executing error

### ISSUE THREAD

**Issue by maple-leaf** [tony/tmux-config#33]
Please refer to this answer of issue at tmuxinator.

https://github.com/tmuxinator/tmuxinator/issues/225#issuecomment-42928000

**Comment by tony** [comment]
> tmuxinator executing error

Can you paste the error that occurs in tmuxp and the config you use?

**Comment by maple-leaf** [comment]
It will raise `can't find pane` error when start session created by tmuxinator.
And I add `pane-base-index` config below your `base-index`:

```
# Start numbering at 1
set -g base-index 1
set -g pane-base-index 1 ## I add this config here
```
