### ISSUE TITLE
Question:  How could I use ctrl-a to jump to the head of the line in tmux

### ISSUE THREAD

**Issue by arthurkiller** [tony/tmux-config#34]
How could I use ctrl-a to jump to the head of the line in tmux

ctrl-a + ctrl-a       can not do this and I don't know why

**Comment by arthurkiller** [comment]
@tony

**Comment by roycyt** [comment]
Try `Ctrl-a a`

**Comment by arthurkiller** [comment]
cool thx @roycyt
