### ISSUE TITLE
tmux 2.9

### ISSUE THREAD

**Issue by grahame** [tony/tmux-config#46]
I was just trying out your config on MacOS using tmux from homebrew, and ran into these errors:

```
/Users/grahame/.tmux.conf:4: invalid option: status-attr                                                               [0/0]
/Users/grahame/.tmux.conf:12: invalid option: window-status-fg
/Users/grahame/.tmux.conf:13: invalid option: window-status-bg
/Users/grahame/.tmux.conf:17: invalid option: window-status-current-fg
/Users/grahame/.tmux.conf:18: invalid option: window-status-current-bg
/Users/grahame/.tmux.conf:22: invalid option: pane-border-fg
/Users/grahame/.tmux.conf:23: invalid option: pane-active-border-fg
/Users/grahame/.tmux.conf:26: invalid option: message-bg
/Users/grahame/.tmux.conf:27: invalid option: message-fg
```

tmux 2.9 only just came out (three days ago), looks like the changes made to style config have broken things:
https://github.com/tmux/tmux/blob/master/CHANGES#L27

(thanks for the example config!)

**Comment by arthurkiller** [comment]
+1 same

**Comment by arthurkiller** [comment]
I have put up an issue for this 
https://github.com/tmux/tmux/issues/1717

**Comment by tony** [comment]
@arthurkiller @grahame Either of you have a PR that'd be backward compatible with older tmux versions?

I'm not sure if it's an issue to be fixed on tmux' end yet

**Comment by xircon** [comment]
Me too, Manjaro Linux, fresh install.  Downgrading to 2.8 no errors, but a blank status line.

**Comment by arthurkiller** [comment]
Author will fix this tomorrow

**Comment by tony** [comment]
@arthurkiller @xircon @grahame Does 094df60   help?

**Comment by arthurkiller** [comment]
I have fixed locally and works well.
