### ISSUE TITLE
syntax error on tmux 3.0a

### ISSUE THREAD

**Issue by haifenghan** [tony/tmux-config#48]
There is an error when running under tmux 3.0a as follows:
`.tmux.conf:100: syntax error`

Could you look into it?

**Comment by Dave-van-der-Meer** [comment]
I actually have the same Issue under Manjaro (after adding the CPU load indicator). On Ubuntu 18.04 I did not add the CPU indicator and it does not show the error.

**Comment by Dave-van-der-Meer** [comment]
Well, I just uninstalled tmux, deleted the .tmux/ folder and the .tmux.conf file and reinstalled tmux with pacman and now it still has the CRTL+A configuration anf the CPU indicator without showing the error message anymore.

**Comment by haifenghan** [comment]
@Dave-van-der-Meer 
I recloned the repo without cup indicator, and now there is no such issue anymore.
Thanks

**Comment by antgel** [comment]
Does anyone have a solution that doesn't involve nuking everything? Does anyone know why that line broke? What does "recloned the repo without cup indicator" mean?
