### ISSUE TITLE
^B shows when pressing ctrl+b 

### ISSUE THREAD

**Issue by errakeshpd** [tony/tmux-config#9]
cant able to execute tmux command after pasting the configuration
ctrl+b --> showing as ^B

![erro](https://cloud.githubusercontent.com/assets/5379778/5514261/66914934-884e-11e4-89d3-e64aaa4a3b7e.png)

**Comment by tony** [comment]
@errakeshpd Have you found a solution for this?

Can you show the output of ``$TERM`` and ``locale``?

Note, the configuration on the repo uses the ``^a`` / ``ctrl-a`` prefix, unlike normal tmux, which defaults to ``ctrl-b``.

**Comment by errakeshpd** [comment]
please find the o/p

![screenshot from 2017-11-10 21-04-47](https://user-images.githubusercontent.com/5379778/32686046-e3c4890a-c65a-11e7-9af5-8225d9bc4e7e.png)
